//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurants
    {
        public int id { get; set; }
        public int idCategory { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
        public string image { get; set; }
        public int orderTable { get; set; }
    
        public virtual categories categories { get; set; }
    }
}
