//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class users
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        public int idRol { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        public string name { get; set; }
        public string lastName { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        public string email { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        public string password { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
